version: '3.8'
services:
  mysqlserver:
    build:
      context: ""
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=smoothstack
      - MYSQL_PASSWORD=smoothstack
      - MYSQL_DATABASE=scrumptious
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:

networks:
  default:
    external:
      name: mysql-spark
