FROM python:3.9.7-buster

WORKDIR /work

COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache -r requirements.txt

COPY ./app ./app
ENV PYTHONPATH="${PYTHONPATH}:${PWD}"

CMD ["python", "-m", "app.consume.kinesis.retry"]
